version: '3.8'

services:
  api:
    container_name: jobs_api
    build: .
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    command: air ./cmd/main.go -b 0.0.0.0
    networks:
      - jobs
  db:
    container_name: jobs_db
    image: postgres:alpine
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - jobs

volumes:
  postgres-db:
    name: jobs-db-volume

networks:
  jobs:
    name: jobs
    driver: bridge