version: '3.8'

services:
  api:
    container_name: jobs_api
    build: .
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    command: air ./cmd/main.go -b 0.0.0.0
    networks:
      - postgres_jobs

networks:
  postgres_jobs:
    external: true